# Generated by Django 3.0.4 on 2021-10-05 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('hotelNo', models.CharField(max_length=100, verbose_name='酒店编号')),
                ('name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('brand', models.CharField(max_length=100, verbose_name='酒店品牌')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('addr', models.CharField(max_length=200, verbose_name='酒店地址')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='房间ID')),
                ('roomNo', models.CharField(max_length=100, verbose_name='房间编号')),
                ('roomType', models.CharField(max_length=100, verbose_name='房间类型')),
                ('countsBed', models.IntegerField(default=0, verbose_name='床数量')),
                ('countsBreakfirst', models.IntegerField(default=0, verbose_name='早餐数量')),
                ('isTwoNightsMore', models.BooleanField(default=False, verbose_name='是否连住2晚及以上')),
                ('checkInDate', models.DateField(default=datetime.date.today, null=True, verbose_name='入住日期')),
                ('checkOutDate', models.DateField(default=datetime.date.today, null=True, verbose_name='离开日期')),
                ('countsMember', models.IntegerField(default=1, verbose_name='入住人数')),
                ('costPrice', models.FloatField(default=0, verbose_name='成本价格')),
                ('roomSyncTime', models.DateTimeField(verbose_name='酒店同步时间')),
                ('agent1', models.CharField(max_length=100, verbose_name='代理商1')),
                ('agent1Price', models.CharField(max_length=100, verbose_name='代理商1价格')),
                ('agent2', models.CharField(max_length=100, verbose_name='代理商2')),
                ('agent2Price', models.CharField(max_length=100, verbose_name='代理商2价格')),
                ('agentSyncTime', models.DateTimeField(verbose_name='代理商同步时间')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
    ]
