# Generated by Django 3.0.4 on 2021-10-05 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='agentSyncTime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='代理商同步时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomSyncTime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='酒店同步时间'),
        ),
    ]
