# Generated by Django 3.0.4 on 2021-10-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20211005_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomSyncTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='酒店同步时间'),
        ),
    ]
