# Generated by Django 3.0.4 on 2021-10-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20211006_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='agentSyncTime',
            field=models.DateTimeField(null=True, verbose_name='代理商同步时间'),
        ),
    ]
