# Generated by Django 3.0.4 on 2021-10-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20211006_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='标题'),
        ),
    ]
